### ISSUE TITLE
EFI Partition Takes Entire Drive (GRUB Installer)

### ISSUE THREAD

**Issue by joshuafhiggins** [ric96/atvx86#11]
You have officially corrupted 800 GB of data. Thank You!

**Comment by F1uk369** [comment]
you're just an idiot and didn't make a separate partition.

**Comment by joshuafhiggins** [comment]
It's been 2 years and regret being passive aggressive when opening this issue instead of detailing my install process. But from what little I remember, I shrunk my 1TB drive to contain multiple OS's and told the installer to install to an empty unused space. Maybe it thought to install the OS there but moved the EFI partition to the begining of the device and smashed through to meet and be next to the OS but it's too long ago for me to remember or care. I also shouldn't have made this issue for this project because it's an addition on top of Android x86, as this would be their issue.

> you're just an idiot and didn't make a separate partition.

Please tell me you have at least tried to install this before commenting.
