### ISSUE TITLE
Updated ISO

### ISSUE THREAD

**Issue by SteinerOkay** [ric96/atvx86#2]
If updated ISO will be avaliable?

**Comment by ric96** [comment]
in a day or two

**Comment by SteinerOkay** [comment]
thanks:)

**Comment by ric96** [comment]
[](http://geektillithertz.com/wordpress/index.php/2016/06/20/android-tv-x86-build-2/)

**Comment by ric96** [comment]
http://geektillithertz.com/wordpress/index.php/2016/06/20/android-tv-x86-build-2/
